// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfoazkxbdvvcvyyfhefx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhmb2F6a3hiZHZ2Y3Z5eWZoZWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTUwNjQsImV4cCI6MjA3MzE5MTA2NH0.1nvWDQiB5_qeutdG_7sXq0oL79x8CX9fI-1KkHYExAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});